Feat/checkout
Shamzaa/TDT4242-Group2 pull request #116
Opened 2018-04-02 12:36 UTC by Aborysa

- Updated shopping cart styling
 - Made it possible to place orders

2018-04-02 15:04 UTC, DeimosA commented on frontend/src/app/app-routing.module.ts
> +import { CheckoutComponent } from './checkout/checkout.component';
What does the checkout component do?

2018-04-02 15:04 UTC, DeimosA commented on frontend/src/app/shopping-cart-list/shopping-cart-list.component.html
> +        <button (click)="updateQty($event, item, 1)" class="btn-flat waves-effect waves-light cart-btn-small"><i class="material-icons cart-icon-btn">add</i></button>
Increment on right side

2018-04-02 15:04 UTC, DeimosA commented on frontend/src/app/shopping-cart-list/shopping-cart-list.component.html
> +      <td class="cart-td-right" *ngIf="productLoaded(item)">{{item.quantity * product(item).price.toFixed(2)}}kr</td>
total calculated price must be toFixed

2018-04-02 15:04 UTC, DeimosA commented on frontend/src/app/shopping-cart-list/shopping-cart-list.component.ts
> +  private totalPrice() : number{
Price calculation must account for sale

2018-04-02 15:04 UTC, DeimosA commented on frontend/src/app/shopping-cart/shopping-cart.component.html
>      Total price: kr {{ totalPrice() }}
toFixed

2018-04-02 15:07 UTC, DeimosA requested changes
see comments

2018-04-02 16:34 UTC, Aborysa commented
What does toFixed do?

2018-04-02 16:48 UTC, DeimosA commented
.toFixed(2) fikserer til 2 decimaler

2018-04-03 12:44 UTC, DeimosA approved these changes

2018-04-03 12:47 UTC, merged