Review/order controller
Shamzaa/TDT4242-Group2 pull request #97
Opened 2018-03-19 13:00 UTC by andreajl

#84 Rewrite into smaller functions, use of promise and functional code.

2018-03-19 19:45 UTC, DeimosA requested changes
;

2018-03-19 23:16 UTC, DeimosA requested changes
- [x] Test products must contain manufacturer
- [x] Confirm/dismiss productId?
- [x] Confirm sets user_confirmed=false
- [x] Order should be dismissable if:
* not confirmed by user
* confirmed by user and with status pending (i.e not accepted or higher status)
* Or just for simplicity; if order status is still pending
- [x] Validate quantity > 0 as in review-backend branch
- [x] /** on first line of function doc (line 95)
- [x] Missing TODO don't allow buying unlisted products (not implemented in frontend)
- [x] Missing orderDetails details. Should be a snapshot of the products at purchase time. At least add manufacturer, price and sale details
- [x] accumelator
- [ ] Price is calculated twice for all order lines
- [x] Price should be fixed to two decimals before summation (really only applicable for percent sale)
- [x] Prefer res.json over res.ok (less overhead)
- [x] Somewhat misleading that most error responses result in 404, and res.negotiate defaults to 500, i.e. Error('User not found') will not be understood.
- [x] Line endings;

2018-03-20 09:13 UTC, Aborysa commented
>Somewhat misleading that most error responses result in 404, and res.negotiate defaults to 500, i.e. Error('User not found') will not be understood.

Does catch pass what error occurred?

2018-03-20 10:27 UTC, DeimosA approved these changes

2018-03-20 11:10 UTC, merged